services:
  dev:
    image: lemonaderoom/claude-code:latest
    tty: true
    volumes:
      - '.:/claude/workspace'
      - '${HOME}/.claude:/claude/.claude'
      - '${HOME}/.claude.json:/claude/.claude.json'
      - '/var/run/docker.sock:/var/run/docker.sock'
